#!/bin/sh

GetPID() { 
    PsUser=$1 
    PsName=$2 
    pid=`ps -u $PsUser|grep $PsName|grep -v grep|grep -v vi|grep -v dbx|grep -v tail|grep -v start|grep -v stop |sed -n 1p |awk '{print $1}'` 
    echo $pid 
}

PID=`GetPID root tcpdump`
echo $PID
if [ $PID -gt 0 ] 
then {
  kill -9 $PID
} else {
  echo "tcpdump didn't run"
}
fi